blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
comment_width = 130
control_brace_style ="AlwaysSameLine"
edition = "2018"
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_args_layout = "Compressed"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Visual"
inline_attribute_width = 0
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 130
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
report_fixme = "Always"
report_todo = "Never"
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
wrap_comments = true